In [6]:
def check(number): # 456
    result = 0
    for i in str(number):
        result += int(i)**3
    if result == number:
        return True
    else:
        return False
        

In [8]:
check(153)

True

In [17]:
def armstrong(number): #789
    num = number #789
    result = 0
    while num>0:
        
        value = num%10
        result += value**3
        num = num // 10
    if result == number:
        return True
    else:
        return False
    

In [18]:
armstrong(153)

True

In [22]:
import numpy as np

In [40]:
a  = [[1,1,1],
      [1,2,1],
      [3,1,3]]

In [41]:
a = np.array(a)

In [42]:
a

array([[1, 1, 1],
       [1, 2, 1],
       [3, 1, 3]])

In [44]:
d1 = 0
d2 = 0
n = len(a)
for i in range(n):
    d1 += a[i][i]
    d2 += a[i][n-i-1]
print(d1+d2)

12


In [46]:
s = len(a)
d1 = 0
d2 = 0
# for 1st diagonal
for i in range(s):
    for j in range(s):
        if i==j:
            d1 += a[i][j]
            
# for 2nd diagonal
for i in range(s):
    for j in range(s):
        if i+j == n-1:
            d2 += a[i][j]
print(d1+d2)

12


In [31]:
lst = [4,5,6]

In [34]:
[(lambda x:x**2 for x in lst)]

[<generator object <genexpr> at 0x0000018712F6E970>]

In [35]:
[x**2 for x in lst]

[16, 25, 36]

In [47]:
'sdf' + 'fd'

'sdffd'

In [54]:
num = int(input())
while num > 1:
    num = num // 3
print(num)    

8
0


In [55]:
8//3

2

In [56]:
2//3

0

In [59]:
for i in range(1,1):
    print(i)

In [60]:
for i in range(2,5):print(i)

2
3
4


In [61]:
# sum of digits
# take T as input for the test case
# for each test case, take integer A as input and print the sum of the digit.(10) -> 1+0 = 1, 46 -> 4+6=10 

In [68]:
def digit():
    T = int(input()) # test case
    while T > 0:
        a = input() # 45
        total = 0
        for i in a:
            total = total + int(i)
        T-=1    
        print(total)
      
        

In [71]:
digit()

1
0
0


In [80]:
def digit2():
    T = int(input())
    while T > 0:
        a = int(input()) # 45
        result = 0
        while a > 0:
            result += a%10
            a //=10
        
        T -=1
        print(result)    

In [81]:
digit2()

2
11
2
78
15


In [75]:
1%10

1

In [74]:
9//10

0

#### PRIME NUMBER

In [107]:
def is_prime(n):
    for i in range(2,int(n/2)+1):
        if n%i==0:
            #print('This is not a prime number')
            return ('This is not a prime number')
        
    return ('This is prime number')

In [110]:
is_prime(43)

'This is prime number'

####  sum of prime numbers 

In [111]:
def is_prime(n):
    for i in range(2,int(n/2)+1):
        if n%i==0:
            #print('This is not a prime number')
            return 0
        
    return n

In [113]:
print(is_prime(410))

0


In [114]:
x = [7,8,6,5,3,11,6]

In [116]:
total = 0
for i in x:
    total += is_prime(i)
print (total)    

26


#### check if sum of prime is prime ?

In [121]:
def check_prime(n):
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return 0
    return n



def check_prime_array(arr):
    total = 0
    for i in arr:
        if check_prime(i):
            total += i
    print(f"Total sum of prime numbers is : {total}")
    
    
    
    
    if check_prime(total) == 0:
        print(f"Sum of prime numbers is not a prime number")
    else:
        print("Sum of prime number is a prime numbe")

In [123]:
check_prime_array([7,3,11,6])

Total sum of prime numbers is : 21
Sum of prime numbers is not a prime number


####  summation of diagonals

In [130]:
a  = [[1,1,1],
      [1,2,1],
      [1,1,3]]

In [131]:
a = np.array(a)

In [132]:
a

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 3]])

In [137]:
def add_diagonals(matrix):
    first_diagonal = 0
    second_diagonal = 0

    n = len(matrix[0])
    for i in range(n):
        first_diagonal += matrix[i][i] 
        second_diagonal += matrix[i][n-i-1]
    print(first_diagonal)   
    print(second_diagonal)

In [138]:
add_diagonals(a)

6
4


#### TRANSPOSE

In [139]:
a

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 3]])

In [140]:
def trans(matrix):
    new = matrix
    n = len(matrix[0])
    
    for i in range(n):
        for j in range(n):
            new[i][j] = matrix[j][i]
    print(new)        

In [141]:
trans(a)

[[1 1 1]
 [1 2 1]
 [1 1 3]]
